### ISSUE TITLE
run on android studio

### ISSUE THREAD

**Issue by mnarbash** [pjasiun/dtmf-decoder#3]
How run dumf-decoder on android studio?

**Comment by mmehdi** [comment]
try this
[android-dtmf-decoder.zip](https://github.com/pjasiun/dtmf-decoder/files/1164918/android-dtmf-decoder.zip)

**Comment by ajaygosh102** [comment]
thks man, its wrking on android studio on lower sdk. not on latest sdk version.

**Comment by AmitPal100001** [comment]
Hello Developers,

It's crashing in my Android studio 
crash report


 Caused by: java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=pl.polidea.apphance.action.START }
        at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1586)
        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1638)
        at android.app.ContextImpl.startService(ContextImpl.java:1610)
        at android.content.ContextWrapper.startService(ContextWrapper.java:680)
        at pl.polidea.apphance.Apphance.start(Apphance.java:239)
        at wpam.recognizer.MainActivity.onCreate(MainActivity.java:49)
        at android.app.Activity.performCreate(Activity.java:7969)
        at android.app.Activity.performCreate(Activity.java:7958)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306

Can you please help me how I can resolve this?

Thanks,
Amit

**Comment by aydinduygu** [comment]
Is there any solution?
I am in same situation
